### ISSUE TITLE
gpio12这个开关是干嘛的?

### ISSUE THREAD

**Issue by seishinkouki** [duck531a98/esp8266-weather-station-epaper#2]
请教
![image](https://user-images.githubusercontent.com/8842321/40229767-d4db9292-5ac7-11e8-89c3-7c02a97e6e50.png)

**Comment by duck531a98** [comment]
那个按钮没有用，我都忘了，好像是想弄个按键，后来发现那个口用不了，好像被什么占用了

**Comment by seishinkouki** [comment]
哦哦, 我还想是干嘛的, gpio12是硬件spi的miso
